---
driver:
  name: vagrant
  vm_hostname: false
  provision: true
  vagrantfiles:
    - vagrantfiles/veos.rb

provisioner:
  name: shell

verifier:
  ruby_bindir: /opt/puppetlabs/puppet/bin

platforms:
  - name: vEOS-4.17.1F
  - name: vEOS-4.16.7M

suites:
  - name: default
